/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.kafka.handson;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Average extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 391382679235247053L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Average\",\"namespace\":\"com.kafka.handson\",\"fields\":[{\"name\":\"average\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Average> ENCODER =
      new BinaryMessageEncoder<Average>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Average> DECODER =
      new BinaryMessageDecoder<Average>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Average> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Average> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Average> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Average>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Average to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Average from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Average instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Average fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private double average;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Average() {}

  /**
   * All-args constructor.
   * @param average The new value for average
   */
  public Average(java.lang.Double average) {
    this.average = average;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return average;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: average = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'average' field.
   * @return The value of the 'average' field.
   */
  public double getAverage() {
    return average;
  }


  /**
   * Sets the value of the 'average' field.
   * @param value the value to set.
   */
  public void setAverage(double value) {
    this.average = value;
  }

  /**
   * Creates a new Average RecordBuilder.
   * @return A new Average RecordBuilder
   */
  public static com.kafka.handson.Average.Builder newBuilder() {
    return new com.kafka.handson.Average.Builder();
  }

  /**
   * Creates a new Average RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Average RecordBuilder
   */
  public static com.kafka.handson.Average.Builder newBuilder(com.kafka.handson.Average.Builder other) {
    if (other == null) {
      return new com.kafka.handson.Average.Builder();
    } else {
      return new com.kafka.handson.Average.Builder(other);
    }
  }

  /**
   * Creates a new Average RecordBuilder by copying an existing Average instance.
   * @param other The existing instance to copy.
   * @return A new Average RecordBuilder
   */
  public static com.kafka.handson.Average.Builder newBuilder(com.kafka.handson.Average other) {
    if (other == null) {
      return new com.kafka.handson.Average.Builder();
    } else {
      return new com.kafka.handson.Average.Builder(other);
    }
  }

  /**
   * RecordBuilder for Average instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Average>
    implements org.apache.avro.data.RecordBuilder<Average> {

    private double average;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.kafka.handson.Average.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.average)) {
        this.average = data().deepCopy(fields()[0].schema(), other.average);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Average instance
     * @param other The existing instance to copy.
     */
    private Builder(com.kafka.handson.Average other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.average)) {
        this.average = data().deepCopy(fields()[0].schema(), other.average);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'average' field.
      * @return The value.
      */
    public double getAverage() {
      return average;
    }


    /**
      * Sets the value of the 'average' field.
      * @param value The value of 'average'.
      * @return This builder.
      */
    public com.kafka.handson.Average.Builder setAverage(double value) {
      validate(fields()[0], value);
      this.average = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'average' field has been set.
      * @return True if the 'average' field has been set, false otherwise.
      */
    public boolean hasAverage() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'average' field.
      * @return This builder.
      */
    public com.kafka.handson.Average.Builder clearAverage() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Average build() {
      try {
        Average record = new Average();
        record.average = fieldSetFlags()[0] ? this.average : (java.lang.Double) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Average>
    WRITER$ = (org.apache.avro.io.DatumWriter<Average>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Average>
    READER$ = (org.apache.avro.io.DatumReader<Average>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.average);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.average = in.readDouble();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.average = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










